### ISSUE TITLE
Immediate invocation on OrDefault()

### ISSUE THREAD

**Issue by jnyrup** [JosefPihrt/Roslynator#110]
In spirit of #104:

```
var list = new List<MyType>();
. . .
list.FirstOrDefault().MyProperty;
list.FirstOrDefault().MyMethod();
```

When `MyType` is a reference type, invocation of a property or an instance method (it may work with extension methods) would cause an NRE.

As one could roll a custom implementation of `FirstOrDefault`, this requires the analyzer to know that it is `System.Linq.FirstOrDefault` being called.

Other extensions methods in `System.Linq` would be `LastOrDefault`, `SingleOrDefault` and `ElementAtOrDefault`.

I think this could only be an analyzer, as there are multiple way to fix it, e.g.
* `list.First().MyMethod()`
* `list.FirstOrDefault()?.MyMethod()`

**Comment by wekempf** [comment]
I don't want to think hard enough to know if this bit of trivia impacts this suggestion or not, but the following behavior of SingleOrDefault has always bugged me.

```csharp
var list = new int[] { 1, 2 };
var result = list.SingleOrDefault();
```

It seems obvious to me that when you call a "OrDefault" method it's a clear indicator you don't know how many items are in the collection. So why in the heck would this case throw an InvalidOperationException instead of returning the default value? Frankly, I think this is a bug. :(

**Comment by IanKemp** [comment]
@wekempf `SingleOrDefault` is intended for collections where you expect either zero or exactly one item, and anything else signifies an error condition. True, it's not a very common case, but it's there if you need it.

**Comment by wekempf** [comment]
"It's not a very common case" is an understatement. The case where I want a single item and anything else to return the default is actually pretty common, but the case that SingleOrDefault gives us isn't one that I've ever encountered, and can't imagine I ever will. :) It's also not "pit of success" design. But, this is mostly off topic, so I'll drop it here. Just wanted someone to think about whether or not this behavior makes a difference in an analyzer like this.

**Comment by JosefPihrt** [comment]
I think this proposal could be combined with #104 into something like: **If the object whose member is being accessed can be null then a null conditional operator should be added**. This would apply to the following cases:

* `(x as Entity).Property` >>> `(x as Entity)?.Property`
* `ElementAtOrDefault().Property` >>> `ElementAtOrDefault()?.Property`
* `FirstOrDefault().Property` >>> `FirstOrDefault()?.Property` (+1 overload)
* `LastOrDefault().Property` >>> `LastOrDefault()?.Property` (+1 overload)

This proposal is not applicable to `SingleOrDefault` as this method throw exception instead of returning default value.
