### ISSUE TITLE
Request: Additional codefix suggestion for RCS1202

### ISSUE THREAD

**Issue by jnyrup** [JosefPihrt/Roslynator#138]
For
```csharp
(variable as T).Property
```
The available codefixes on the `as` token are "replace as with cast" and "Use conditional access".
On `.` "Use conditional access" is available.

Is it possible to add multiple codefix suggestions for the same analyzer, so RCS1202 would list both codefixes on the `.`?

**Comment by JosefPihrt** [comment]
[ReplaceAsWithCast](http://github.com/JosefPihrt/Roslynator/blob/master/docs/refactorings/ReplaceAsWithCast.md) is refactoring so it is available only within span of 'as expression'.

Code fix should not change semantics which is what this refactoring does.

**Comment by jnyrup** [comment]
Isn't changing `(value as T).Member` to `(value as T)?.Member` also a change in semantics?
To me changing an NRE to an InvalidCastException seems to be a smaller semantic change, than either not invoking a member.

**Comment by jnyrup** [comment]
Replacing with conditional access can even be a syntactic change when expecting the return type to be a value type.

```csharp
int value = (obj as MyClass).MyIntProperty;
```

**Comment by JosefPihrt** [comment]
I agree that adding conditional access can be syntactic change.

I still don't think that it is a  good code fix to exchange a risk of one exception for another.

Also I think that if you use 'as' operator there is a reason for it. Your code fix would make sense if you know for sure that expression can be casted to T. But this problem is not related to analyzer UseConditionalAccess.
