### ISSUE TITLE
Adjust analyzer default settings - "DefaultSeverity", "IsEnabledByDefault"

### ISSUE THREAD

**Issue by JosefPihrt** [JosefPihrt/Roslynator#14]
Leave a comment

**Comment by huoyaoyuan** [comment]
Example: `RCS1025`~`RCS1028`
They can be categorized as "coding style: line separating".
For who follows these rules, they can set these default to `Information`; and for who doesn't follow, they can set to `Hidden`.

**Comment by JosefPihrt** [comment]
My understanding is that only one value can be set as default, not two.

**Comment by huoyaoyuan** [comment]
My opinion is, that "styles" should be optional, while "rules" are constant. I think they can even be separated into two packages.
I use [CodeMaid](https://github.com/codecadwallader/codemaid) for code styling: it's only about styling, no analysis. And I want a package that contains only analysis, no styling.
In my understanding, "analysis" and "refactor" is for expression tree. Using new language features are also contained. Otherwise, "styling" is for something that does not change the expression tree, or just reordering.
So I think it's reasonable to provide two packages.
