### ISSUE TITLE
RCS1158 is suggested for const fields

### ISSUE THREAD

**Issue by jhinder** [JosefPihrt/Roslynator#162]
Constant fields are implicitly static (`.field static literal` in CIL), thus RCS1158 will be suggested for them.

However const fields have special behaviour (compile-time constant, restricted list of possible types, compilers have to replace any field access with the literal value) compared to regular static fields, so I think this analyzer should exclude const fields.

**Comment by JosefPihrt** [comment]
I understand that constants have different behaviour than fields. I'm not clear how it is related to RCS1158.

If you look at the code below you see that when you want to access constant you have to specify type argument which is confusing because there is not relation between type argument and constant value.

```csharp
public class Foo<T>
{
    public const string Constant = "x"; // RCS1158

    public void Bar()
    {
        string s1 = Foo<string>.Constant; // "x"
        string s2 = Foo<int>.Constant; // "x"
    }
}
```

Could you provide a code sample where you think that RCS1158 should be excluded?
