### ISSUE TITLE
Backwards performance warning

### ISSUE THREAD

**Issue by adameska** [JosefPihrt/Roslynator#178]
https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1080.md 
Why does this think Count > 0 is more performant than Any() ? I've always been told the opposite.

**Comment by jnyrup** [comment]
You've probably been told that `Any()` is more performant than `Count() > 0`.
`Count` is a property, that all classes implementing `ICollection<T>` or similar collection interfaces has, while `Count()` is an extension method in LINQ.

Have a look at their [implementations](http://referencesource.microsoft.com/#System.Core/System/Linq/Enumerable.cs,56cc4347faaef1e1) of `Any()` and `Count()`

`Any()` tries to a single enumeration of `source` to see if it has _any_ elements.
```c#
public static bool Any<TSource>(this IEnumerable<TSource> source) {
	if (source == null) throw Error.ArgumentNull("source");
	using (IEnumerator<TSource> e = source.GetEnumerator()) {
		if (e.MoveNext()) return true;
	}
	return false;
}
```

`Count()` works by first checking if `source` implements `ICollection`/`ICollection<T>` and if so use its `Count` property.
Otherwise it counts the number of elements by enumerating the entire sequence.
```c#
public static int Count<TSource>(this IEnumerable<TSource> source) {
	if (source == null) throw Error.ArgumentNull("source");
	ICollection<TSource> collectionoft = source as ICollection<TSource>;
	if (collectionoft != null) return collectionoft.Count;
	ICollection collection = source as ICollection;
	if (collection != null) return collection.Count;
	int count = 0;
	using (IEnumerator<TSource> e = source.GetEnumerator()) {
		checked {
			while (e.MoveNext()) count++;
		}
	}
	return count;
}
```

So `.Count > 0` is the fastest as it only has to compare the property (which is fast to get) to `0`.
Whether `.Count() > 0` or `.Any()` is the slowest depends on the collection type.

**Comment by JosefPihrt** [comment]
Thanks @jnyrup  for explanation.

I would add that calling `Enumerable.Any/Count` may cause allocation if an enumerator is class.

**Comment by markusrt** [comment]
@JosefPihrt Are there any plans to incorporate usefull explanations like the one above to the corresponding rules markdown file?

I just found myself using google to search the rational behind two rules. I.e. having this in the markdown would really be great :)

**Comment by JosefPihrt** [comment]
@markusrt Any contribution that will improve documentation is welcome.

I added [instructions](https://github.com/JosefPihrt/Roslynator/blob/master/docs/HowToUpdateDocumentation.md) on how to update documentation.

**Comment by StijnOttenVMT** [comment]
current [Linq Any()](https://source.dot.net/System.Linq/R/8788153112b7ffd0.html) has been updated to include a check for is ICollection. Therefore any is as performant as count would be.\

Using Any() is now preferred because performance is the same or very similar and Any() is more universal.

I'll make a new issue about it
