### ISSUE TITLE
RCS1109 flaw with refactoring when type conversion via custom cast operators

### ISSUE THREAD

**Issue by LesRamer** [JosefPihrt/Roslynator#186]
[RCS1109](https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1109.md): Call 'Enumerable.Cast' instead of 'Enumerable.Select'

Consider the following example:
```csharp
public class Foo
{
}

public class Bar
{
    public static explicit operator Foo(Bar bar) => new Foo();
}

// usage
var fooSelect = Enumerable.Repeat(new Bar(), 1)
    .Select(b => (Foo)b) // RCS1109 wants to replace this line
    .ToList(); // this works, it builds the list

var fooCast = Enumerable.Repeat(new Bar(), 1)
    .Cast<Foo>() // RCS1109 wants to replace the above Select with this Cast 
    .ToList(); // enumerating to build list throws InvalidOperationException
```
This illustrates that RCS1109 is not always safe. However, I do believe we can detect when it is safe because we know both the type of the source enumerable that Select is acting upon and we also know the type that it projecting to via a cast. If the types are properly related only then is the Cast<> operator a good replacement. In the case that I'm writing about, the types are only related through the explicit custom cast operator which fails in this case.

**Comment by LesRamer** [comment]
Edit: In my haste, I wrote "InvalidOperationException"  when I meant "InvalidCastException".
Apologies.

**Comment by wekempf** [comment]
This one will confuse a LOT of people. It's a problem caused by the fact that C# has generics, not templates. What the generic method does has to be fully compiled at the source, and not left to being compiled when it's actually used. Because this example has no type constraints, the compiler has to treat the TSource generic parameter as if it's type where System.Object. This means there's no way to dispatch to the explicit cast operator (System.Object doesn't have one). So, the cast in the original Select statement will work, because the compiler can dispatch to the cast operator, while the Cast statement will fail because it doesn't know how to dispatch to it. It's a real mind bender for most, and I'm sure my description still leaves several people baffled by this behavior (LOL).
