### ISSUE TITLE
Refactor Request: Introduce method for lambda expression (anonymous method)

### ISSUE THREAD

**Issue by wmjordan** [JosefPihrt/Roslynator#268]
Given the following code:

````C#
void HookEvents() {
   textView.Closed += (s, args) => {
	tagger.Dispose();
   };
}
````

After refactoring, it produces:
````C#
void HookEvents() {
   textView.Closed += TextView_Closed;
}

void TextView_Closed(object sender, EventArgs e) {
	tagger.Dispose();
}
````

**Comment by LesRamer** [comment]
👍 I like this feature-request.

When locals are not referenced in the lambda, we would want to use a standard-scoped method. Otherwise, locals referenced in the lambda present an interesting wrinkle; a problem that could be solved nicely with a [c# 7.0 Local-Function](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7#local-functions) that has visibility to local variables.

**Comment by wmjordan** [comment]
I can live with an implementation that leaving the local references broken. Manually fixing those would not be to hard.

**Comment by JosefPihrt** [comment]
@wmjordan Can you clarify if you want to create a method or a local function?

**Comment by wmjordan** [comment]
I'd love to have a method.
The reason while I need this refactoring is that sometimes we have some event handlers which initially implemented with lambda expressions and later needed to be unsubscribed during program evolvement, thus the lambda expressions had to be converted to methods so that they could be unsubscribed.
Local functions may not be suitable for this type of scenario.

**Comment by JosefPihrt** [comment]
I see. It makes sense to have a refactoring like this.

Given the existing built-in refactoring "Extract method" a suitable name for this refactoring would be "Extract event handler method".
