### ISSUE TITLE
RCS1207: fix is ambiguous with Task.Run

### ISSUE THREAD

**Issue by wiz0u** [JosefPihrt/Roslynator#289]
The code `m_task = Task.Run(() => MyFunc());` leads to the following error after being fixed by RCS1207

`The call is ambiguous between the following methods or properties: 'Task.Run<TResult>(Func<TResult>)' and 'Task.Run(Func<Task>)'`

(same with the `cancellationToken` variant)

**Comment by Debbus72** [comment]
Funny, I got the same error when I was looking into the TPL DataFlow block yesterday. 
![image](https://user-images.githubusercontent.com/34112915/36679740-43957872-1b14-11e8-982d-19a37b5fc89b.png)

Just a question, is this difficult to detect? Because there is always the possibility that after the fix there are overloads that can apply... or is this now specific to Action<T1> and Func<T1,T2>?

**Comment by JosefPihrt** [comment]
@Debbus72 Could you please provide a code sample that will reproduce the bug?
