### ISSUE TITLE
Add missing semicolon

### ISSUE THREAD

**Issue by kentcb** [JosefPihrt/Roslynator#35]
Hi,

Thanks for this amazing set of analyzers 💯 🎉 

The *Add missing semicolon* analyzer is causing me some stress because:

1. It always appears first, generally ahead of the analyzer I _actually_ want to invoke (add `using` statement)
2. It doesn't appear that I can disable this specific analyzer

Any thoughts on getting this rectified?

**Comment by JosefPihrt** [comment]
Hi,

I'm glad that you like my work.

I noticed that this analyzer appears when it is not desirable.

One option would be to disable it using rule set (Solution Explorer - Solution - Project - References - Analyzers - Open Active Rule Set). This can be done by you.

But in this case it will be probably better to disable it by default since it is more annoying than helping. This has to be done by me.

**Comment by kentcb** [comment]
Thanks @JosefPihrt.

Any idea when you'll be doing another release?

**Comment by JosefPihrt** [comment]
VS extension has been released.

**Comment by kentcb** [comment]
Ah, so it has - thanks. For some reason VS had disabled the add-on.

Also FYI, the docs for the Roslynator add-on (both 2015 and 2017) still includes RCS1122 in the list.
