### ISSUE TITLE
NotifyPropertyChanged to RaisePropertyChanged(nameof(

### ISSUE THREAD

**Issue by nawlins** [JosefPihrt/Roslynator#385]
Hi, Josef.  Your rosalyn tool is so very helpful...thank you.   I can't seem to find out if the refactorings are editable in some way, though.  Is there a way to change the NotifyProperyChanged refactor to a RaisePropertyChanged(nameof([PropertyName])) correction?

Or better yet, even a way to create new raisepropertychanged refactoring that would convert a property like "public string TestName{get; set;}" to a full property with backing field plus the raisepropertychanged if value changed code?

**Comment by JosefPihrt** [comment]
Hi,

I'm glad you like Roslynator.

Could you please provide a reference (a link) to `RaisePropertyChanged` API? I'm not familiar with it.

**Comment by Kirides** [comment]
i think he means the default method of raising property notifications that is often found instead of `OnPropertyChanged`. It shares the same interface `public void RaisePropertyChanged(string propertyName)` (often found as `RaisePropertyChanged([CallerMemberName]string propertyName = null)`) but it's name is more expressive about what executing it means. (e.g. it _raises_ a `PropertyChanged`-event)
