### ISSUE TITLE
Interference on CS0219: Code fix incorrect for VS17 15.8.0 preview 4

### ISSUE THREAD

**Issue by MSeifert04** [JosefPihrt/Roslynator#413]
The situation: The fix for CS0219 in Rosyln was incorrect, however it has been fixed (https://github.com/dotnet/roslyn/pull/24077) recently and the correct code fix should be available in VS 2017 15.8.0 preview. However when Roslynator is installed and running the **incorrect** code fix is applied (see also https://github.com/dotnet/roslyn/issues/28704). Disabling Roslynator makes the corrected code-fix from rosyln available.

Is it possible that Roslynator overwrites the roslyn code-fix or interferes there in some (unintended) way?

**Comment by JosefPihrt** [comment]
Roslynator provides a lot of code fixes for CS diagnostics:
https://github.com/JosefPihrt/Roslynator/blob/master/src/CodeFixes/README.md

Roslynator also provides a code fix for CS0219. Since it became available as a built-in code fix, Roslynator code fix can be removed.

To your question: It is possible if the two code fixes have the same title. Then the Roslynator code fix is displayed instead of built-in code fix. This behavior is defined by Microsoft, not by me.

**Comment by MSeifert04** [comment]
Ah thank you for the explanation. So instead of totally disabling Roslynator I could simply disable the code-fix for CS0219?

**Comment by JosefPihrt** [comment]
Yes, you can.
