### ISSUE TITLE
RCS1231 ("Make parameter ref readonly") suggests API-breaking changes

### ISSUE THREAD

**Issue by mgravell** [JosefPihrt/Roslynator#465]
presumably related to https://github.com/JosefPihrt/Roslynator/commit/6fd8861dadfe8a477e828fcc3cd5f1c701a59745 ?

But: I'm seeing this on `public` APIs on `public` types, including constructors and operators. I realize that the suggestion is not without merit, but I don't think most people are aware that adding `in` here is a fundamentally API-breaking change that will smash compatibility.

tl,dr: this seems a dangerous recommendation for anything `public`

**Comment by mikernet** [comment]
Should this even be a recommendation? I haven't fully fleshed out my understanding of `readonly` structs so perhaps I'm missing something, but it would seem to me that small `readonly` structs are better left passed in normally instead of by ref. 

I can't find any information regarding "best practices" involving `readonly` structs - is it best practice to apply `readonly` to all structs that are read-only regardless of size to enforce read-onlyness within the struct, or only to larger structs that *should* be passed by ref? I guess if it's the latter then this recommendation makes sense, but I've been applying `readonly` to all structs that are intended to be read-only.

**Comment by mgravell** [comment]
I'd concur with the "larger only" - but I suspect that's hard to detect, especially for external types.

**Comment by JosefPihrt** [comment]
I understand you concerns regarding this analyzer. I think that it is reasonable to disable it by default.

**Comment by JosefPihrt** [comment]
Could you share some links to articles that discuss (not) passing read-only structs by ref depending on their size?

**Comment by mgravell** [comment]
@JosefPihrt guidance is limited; example: https://github.com/aspnet/AspNetCore/issues/7180
