### ISSUE TITLE
RR0023 (change 'var' to explicit type) does nothing

### ISSUE THREAD

**Issue by wiz0u** [JosefPihrt/Roslynator#488]
with the following example line:
`int x = 3;`
the Actions menu offers:
- Change type to 'var' _(RR0018)_
- Use implicit type _(native VS refactoring?)_

Both of these work as expected, giving the line
`var x = 3;`

When I activate the Actions menu again, it now offers:
- Change type to 'int' _(RR0023)_
- Use explicit type _(native VS refactoring?)_

RR0023 does nothing. While "Use explicit type" works as expected.

You may want to fix RR0023, or maybe remove RR0018 & RR0023 altogether, as they seem redundant with VS native refactoring actions.

**Comment by JosefPihrt** [comment]
I'm not able to reproduce "RR0023 does nothing" behavior. Which version of Roslynator do you use?

**Comment by wiz0u** [comment]
Roslynator 2017 v2.0.2 with VS 2017 15.9.5

**Comment by JosefPihrt** [comment]
You are right, this behavior is caused by `csharp_style_var_for_built_in_types`.

There is `SyntaxAnnotation` [DoNotAllowVarAnnotation](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Simplification/DoNotAllowVarAnnotation.cs,9f01c09c0741fee5) which only purpose is to prevent `int` from being simplified into `var` even if `csharp_style_var_for_built_in_types` is set. Unfortunately this class is internal and use singleton instance to check if a node is annotated with this annotation.

If roslyn would internally use `SyntaxAnnotation.Kind` to check if a node is annotated then I would be able to create my own `DoNotAllowVarAnnotation` in Roslynator.

I will probably file an issue in roslyn regarding this problem.

Right now (and definitely for Roslynator 2017) this behavior have to be considered as "by design".

The fix is obvious: to disable RR0023.

**Comment by wiz0u** [comment]
Seeing there is already native VS refactoring actions that already does the job of changing int <-> var, I disabled RR0023 & RR0018

**Comment by JosefPihrt** [comment]
https://github.com/dotnet/roslyn/issues/32567
