### ISSUE TITLE
Suggestion: Add config switch to disable info/warning/error messages in VS2019

### ISSUE THREAD

**Issue by lukasf** [JosefPihrt/Roslynator#515]
It would be nice if we could disable all Roslynator messages in the errors window. Lightbulp actions should still appear for all those items.

In older versions, there was a separate extension with just refactorings (without analyzer). But for VS2019, there is only the combined version available. It would be best if there is only one Roslynator extension, but Refactorings and Analyzers could be switched on/off separately in the settings.

**Comment by wmjordan** [comment]
Add one.
I used the refactor on VS 2017 only.

**Comment by JosefPihrt** [comment]
I'm going to introduce new feature that will replace "Global Suppressions" and should meet your demands.

There will be file `roslynator.ruleset` in the directory where Roslynator extension is installed.

This file will be a standard rule set in a sense that it will make possible to disable/enable specific analyzer or to change its severity (action).
It also will make possible to disable/enable all analyzers or to change severity of all analyzers.

It won't be a standard rule set in a sense that it will be neccessary to restart Visual Studio for changes to take effect.

The extension directory is deleted during installation of the update.
That means will be necessary to 1) backup the rule set 2) install the update 3) copy the rule set back to the extension directory.

This feature will be available starting from Roslynator 2019.
The reason for this is that Roslynator 2017 use Roslyn 2.3.* which targets .NET Standard 1.3 which does not expose property Assembly.Location.

@lukasf
You would like to see messages in the lightbulb menu but not in the Error List. This is equal to set severity to 'Hidden'.
Your roslynator.ruleset should look like this.
```xml
<?xml version="1.0" encoding="utf-8"?>
<RuleSet Name="roslynator.ruleset" ToolsVersion="16.0">
  <IncludeAll Action="Hidden" />
</RuleSet>
```

@wmjordan
You would like to disable all analyzers.
Your roslynator.ruleset should look like this.
```xml
<?xml version="1.0" encoding="utf-8"?>
<RuleSet Name="roslynator.ruleset" ToolsVersion="16.0">
  <IncludeAll Action="None" />
</RuleSet>
```
By the way same result can be achieved by deleting assembly Roslynator.CSharp.Analyzers.dll (Roslynator.CSharp.Analyzers.CodeFixes.dll can be deleted as well because it is useless without the former).

**Comment by lukasf** [comment]
This sounds great! 👍 

Is it perhaps possible to store the rule file in a different folder, like %APPDATA%\Roslynator? Accessible also through Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)... Then the file would survive updates.

**Comment by wmjordan** [comment]
@lukasf I agree. I have a VS extension (https://github.com/wmjordan/Codist) which handles configurations like that. No need to backup and restoring the configuration file during updates.

**Comment by JosefPihrt** [comment]
I have incorporated your suggestions. The configuration will be loaded from `%LOCALAPPDATA%\JosefPihrt\Roslynator\VisualStudio\2019\roslynator.ruleset`.

**Comment by JosefPihrt** [comment]
The feature is available in Roslynator 2019 2.1.0.

**Comment by wmjordan** [comment]
I downloaded the 2.1.0. The ruleset in the options page was referring to the extension folder like the following: VisualStudio\16.0_015eb8c4\Extensions\n25i5hhm.xeg

**Comment by JosefPihrt** [comment]
Please read the rule set file which contains the instructions.

**Comment by wmjordan** [comment]
I opened that file with Visual Studio, but saw no extra instructions.
Wasn't it supposed to be `%LOCALAPPDATA%\JosefPihrt\Roslynator\VisualStudio\2019\roslynator.ruleset`? I did not find a file there.

**Comment by wmjordan** [comment]
Well, I just opened that rule set file with a text editor and saw the instructions.

I think it is better to create an empty rule set file in the aforementioned location if no one is there, when a user is clicking the "Location" button in the options page. So we don't have to "move it" to such an obscure place like "%LOCALAPPDATA%\JosefPihrt\Roslynator\VisualStudio\2019"--there are so many folders we have to create manually!

More instructions may be placed in the options page, for instance.
- Could we edit that rule set file with Visual Studio?
- When will the modifications take place?
....

**Comment by lukasf** [comment]
Thank you @JosefPihrt, it works great! I had no problems to get the file working.

But I agree with @wmjordan, it would be a good idea to open the file from the target location on button press. And if the target file or folder does not yet exist, create/copy it. That would make it easier to use this functionality. Indeed it is a bit complicated to manually fiddle out the paths and do the copying.

Having edit capabilities in the settings would be nice to have, but not mandatory from my side. It would be difficult to create an editor that has the whole power of the ruleset file. And if it does not have all capabilities, it might destroy manual changes to the file. So it would have to be a full-blown solution right from the start, which is maybe a bit over the top. If the button from the settings directly opens the target file, it is easy enough from my side.

**Comment by wmjordan** [comment]
@lukasf VS has a built-in editor for ruleset files.
My first attempt against the provided ruleset file was dragging it into VS and modifying its settings.
After saving the file, instructions in the file was removed.

I am not sure whether the built-in ruleset editor works for Roslynator.

**Comment by lukasf** [comment]
@wmjordan I used notepad to edit the file, I did not know VS has an editor. Just checked it out, looks good! If Roslynator would take care of copying the file to the right location, we would not even need the instructions. Then Roslynator could even open the file with VS editor right away, from the right location (after copying it).

**Comment by lukasf** [comment]
I have created a small PR to do the file copying on button press. I am not sure if it is a good idea to open the file directly with an editor. So I left the current behavior of just opening Explorer with the file selected.

**Comment by lostmsu** [comment]
@JosefPihrt I want to clarify. If I set them all to Hidden or None in that file, and then install Roslynator analyzers NuGet, will I get them back?

The problem I am trying to solve is that I don't want Roslynator rules to be shown unless I explicitly install the NuGet package with analyzers.

**Comment by JosefPihrt** [comment]
Roslynator ruleset file does not affect Roslynator analyzers installed as nuget. So answer to your question is yes.
