### ISSUE TITLE
Roslynator DLLs are copied to output

### ISSUE THREAD

**Issue by salixzs** [JosefPihrt/Roslynator#540]
**Product and Version Used**: 
Roslynator.Core, CSharp & CSharp.Workspaces (new extended...)
Visual Studio 2019

**Steps to Reproduce**:
1) In VS2019, create new ASP.NET Core 3 .Net Core 3.0 (Preview 4) Solution (I had several project in it, based on .Net Standard 2.0)
2) Add these new Roslynator extended libs to all projects in solution
3) Publish ASP.NET project to local folder.

**Actual Behavior**:
`bin\Release\netcoreapp3.0\publish` folder contains `Roslynator.*.DLL`-s and also some additional DLL (dependencies, I guess).

**Expected Behavior**:
`bin\Release\netcoreapp3.0\publish` contains only DLLs, necessary for runtime.

**Comment by JosefPihrt** [comment]
I'm not sure but it seems that you want to install Roslynator packages for the purpose of code analysis. In that case please use just package Roslynator.Analyzers.

Nuget packages Roslynator.Core, CSharp & CSharp.Workspaces are standard API libraries, not analyzer assemblies. They are intended to be used for development of analyzers/refactorings.

**Comment by salixzs** [comment]
Using just `Analyzers` is OK. Maybe I did not get the idea of which NuGets should be added.
Honestly - it is not obvious which ones a "common consumer" should install. If those CSharp and other NuGet packages are for development of analyzers themselves - maybe it somehow whould be noted in first page of this GitHub, otherwise I installed all ;-)
Also it is hard to understand right away for normal users - is Roslynator overriding, appending or having completely separate rules to standard `Microsoft.CodeAnalysis.*` namespace analyzers. 
(e.g. do they check the same things in code or different?)

>Package Roslynator.CSharp is a must-have for Roslyn-based development.

Does it mean it should be used (added) when I use Roslyn as compiler for my project -OR- it should be used when I create my own analysis rules.

Otherwise I have high hopes to keep our code clean with your analyzers - great thanks for your work and patience with all of us!

**Comment by GaTechThomas** [comment]
I completely agree with @salixzs. I just spent half an hour trying to determine what the Roslynator.CSharp package is. This issue is the only documentation I've found to that point. Just would be helpful to add a few words to the nuget package description, which currently reads, "This library extends functionality of package Microsoft.CodeAnalysis.CSharp."

Thanks.

**Comment by JosefPihrt** [comment]
First of all, please do not comment closed issues. As CONTRIBUTING.MD states:
```
* **DO** create a new issue rather than commenting a closed issue.
```
\
I agree that description that is part of Roslynator API packages is not perfect. To my defense, project's README.md has section "Roslynator API" which states:
```
* Roslynator API is meant be used for development of your own analyzers/refactorings.
* It does not contain any analyzers/refactorings itself.
```

Another thing is that changing package description would require new release of Roslynator API packages which is doable, but not planned in nearest future.

**Comment by GaTechThomas** [comment]
Thank you very much for this project. It is amazing. Please don't feel like you're having to defend these sorts of questions. The intent is to save others the same trouble in the future, which is also the reason for the comment on this closed issue, otherwise, the topic is redundant and comes with additional overhead.

I think that the reason that I didn't find the Roslynator API info is that it doesn't call out the other nuget packages by name. Putting a statement on the project readme that includes the package names would go a long way to making it easier to understand.

Another request is to put the API description change on the backlog so that if/when it is updated in the future, the idea isn't lost.

I'd be willing to submit a PR for the readme if you're open to it.

Thanks again.
