### ISSUE TITLE
NuGet and VSX in parallel

### ISSUE THREAD

**Issue by wilhelmmedetz** [JosefPihrt/Roslynator#570]
Hi,

I have some understanding questions.

I use both the NuGet package (to force other people to get analyzer warnings) but also the VSX extension (to get the refactorings).

- Does this approach cause problems?
- Does this have performance disadvantages - do the analyzers run twice in parallel?
- Wich analyzer NuGet/VSX is used if the analyzers have different versions?

btw - thanks for these fantastic tool

**Comment by JosefPihrt** [comment]
Hi,

I'm glad that you like Roslynator.

If you use both VSIX and package **Roslynator.Analyzers** it is necessary to ensure that analyzers won't run twice. The solution differs by VS version:

#### VS 2017

Use VSIX **Roslynator Refactorings 2017** which does not contain analyzers.

#### VS 2019

Add following content to file `%LOCALAPPDATA%\JosefPihrt\Roslynator\VisualStudio\2019\roslynator.ruleset`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<RuleSet Name="roslynator.ruleset" ToolsVersion="16.0">
  <IncludeAll Action="None" />
</RuleSet>
```

This will effectively disable all analyzers in VSIX. If you want to play with configuration you can enable new analyzers that are contained only in VSIX (because new version of package has not been published yet).

I hope it helps.

**Comment by wilhelmmedetz** [comment]
Thanks for the explanation.

**Comment by JosefPihrt** [comment]
https://github.com/JosefPihrt/Roslynator/blob/master/docs/HowToUseBothVsixAndNuGet.md

**Comment by wilhelmmedetz** [comment]
Does not seem to work. I copied above roslynator.ruleset, but do get RCS* warnings.
NuGet package is not referenced.

- Visual Studio Enterprise 16.3.7
- Roslynator 2019 2.2.0

Can I provide any additional information?

**Comment by JosefPihrt** [comment]
I have just checked that approach described in my post above works correctly.

My guess is that you have ruleset on a project level which overrides default configuration.

Effective configuration = default configuration + project configuration

Example:
RCS1018 is enabled by default and has default severity 'Info'.
If you apply `<IncludeAll Action="None" />` RCS1018 will be disabled by default.
But if your project has ruleset that specify `<Rule Id="RCS1018" Action="Warning" />` then RCS1018 will be effectively enabled as 'Warning'.

**Comment by wilhelmmedetz** [comment]
Thanks for the fast reply.

This was exactly the reason, one project still referenced an old ruleset.
After removing the ruleset, no warnings wer displayed from the VSX analyzer.
