### ISSUE TITLE
enhancement: simplify `a ? false : b`

### ISSUE THREAD

**Issue by Spongman** [JosefPihrt/Roslynator#612]
**Product and Version Used**: 2.2.0

**Steps to Reproduce**:

get refactorings for `a ? false : b`

**Actual Behavior**:
no simplification

**Expected Behavior**:
simplification: `!a && b`

**Comment by LesRamer** [comment]
Here's that expression and 3 more that I would also expect to simplify:

| expression | &rArr;  | simplified |
|:-----------:| --- |:------:|
| **a ? false : b** |  | **!a && b** |
| a ? true : b |  | a \|\| b |
| a ? b : false |  | a && b |
| a ? b : true |  | !a \|\| b |

**Comment by wiz0u** [comment]
Make sure b is `bool`, because these simplified expressions don't work if b is `bool?` for example

**Comment by JosefPihrt** [comment]
@LesRamer 2nd and 4th case is already covered by [RCS1104](https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1104.md). The other two ones are tricky because there is a negation which can lead to less readable code.

It would be useful to add refactoring (not analyzer) that would simplify these two remaining cases.
