### ISSUE TITLE
RCS1023: FormatEmptyBlock and RCS1076: FormatDeclarationBraces missing from settings

### ISSUE THREAD

**Issue by NickCraver** [JosefPihrt/Roslynator#62]
I'm trying to disable RCS1023 and RCS1076, but they don't appear in settings - possibly just missing from [Refactorings.xml](https://github.com/JosefPihrt/Roslynator/blob/22dc4f8a60c8039896c10190779b767b1bdbb57e/source/Refactorings/Refactorings.xml)?

**Comment by JosefPihrt** [comment]
If it has a prefix "RCS..." then it is analyzer. Please see [How to Customize Analyzers](http://github.com/JosefPihrt/Roslynator/blob/master/docs/HowToCustomizeAnalyzers.md).

I agree that options page is confusing because it may seems that you can disable analyzers from there.

Very soon I'm going to publish new version which will introduce new options page with WPF control instead of PropertyGrid. And it will display code like 'RR...." for each refactoring to avoid confusion with analyzers.

**Comment by JosefPihrt** [comment]
I'm not sure if I'm following you. What are you suggesting?

**Comment by NickCraver** [comment]
@JosefPihrt I just mean in the new settings screen, perhaps have a small section that points people to https://github.com/JosefPihrt/Roslynator/blob/master/docs/HowToCustomizeAnalyzers.md for cutomizing analyzers, so most can help themselves - I looked and couldn't find the expected way of doing it inside the tooling. I think a small description + link would help a lot here, that's all :)

**Comment by JosefPihrt** [comment]
Oh, I see.

I will think about that.
