### ISSUE TITLE
Suggestion: DataContract/DataMember analyzers and quick-fixes

### ISSUE THREAD

**Issue by PhilPJL** [JosefPihrt/Roslynator#638]
If we have code containing DataContractSerializable types like this:

```
[DataContract]
public class AnEntity
{
  [DataMember] public string BProp {get; set;}
  [DataMember] public string AProp {get; set;}
  [DataMember(Order = 5)] public string ZProp {get; set;}
}
```

Given that in general it's better to have explicit naming and ordering of DataContract and DataMember, then it would be useful to have a quick fix to produce this:

```
[DataContract(Name="AnEntity")]
public class AnEntity
{
  [DataMember(Name = "BProp", Order = 2)] public string BProp {get; set;}
  [DataMember(Name = "AProp", Order = 1)] public string AProp {get; set;}
  [DataMember(Name = "ZProp", Order = 3)] public string ZProp {get; set;}
}
```

The ordering should follow the [DataContract ordering rules](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/data-member-order), but should also take into account any existing explicit ordering so that the new explicit ordering should be backward compatible with the previous implicit ordering and not break any existing WCF code.

My primary reason for wanting this (apart from those given above) is to be compatible with gRPC requirements for explicit ordering of properties.  Then using [protobuf-net](https://github.com/protobuf-net/protobuf-net.Grpc) I can easily migrate WCF services to gRPC.

I'm happy to have a go at implementing this.

That's the main case, but there are clearly various permutations of analyzers / fixes that could be implemented.

**Comment by PhilPJL** [comment]
@JosefPihrt 
I've completed my first analyzer and fix here [https://github.com/PhilPJL/Roslynator](https://github.com/PhilPJL/Roslynator).  It's in

`MakeDataContractNamesAndOrderExplicitAnalyzer`
and 
`MakeDataContractNamesAndOrderExplicitCodeFixProvider`

For development I've used id

`public const string MakeDataContractNamesAndOrderExplicit = "PJL0001";
`

If you think it's suitable to add to your project could you assign an id or should I use RCS1242?
I'll get on with unit tests in the meantime.

**Comment by PhilPJL** [comment]
@JosefPihrt 
I've added tests.  
Would you like me to submit a pull request?

**Comment by JosefPihrt** [comment]
Hi,

thanks for your effort. 

However, I think that this kind of analyzer is not suitable for a general set of analyzers (i.e. Roslynator for VS/VS Code or Roslynator.Analyzers).

Maybe this analyzer could be part of a collection of serialization analyzers. But that would need more analyzers (at least ~10).

Regarding the code, it would need a lot of refactoring:
 * Instead of start from syntax (RegisterSyntaxNodeAction) it would be better to start from symbol (RegisterSymbolAction).
 * Heavy usage of LINQ is discouraged because of the performance.
 * Use tuple type instead of anonymous type to reduce allocation.
 * Use ToImmutableArray instead of ToList to reduce allocation.

**Comment by PhilPJL** [comment]
Thanks for taking a look.  I suspected it might be a bit to specialised. If I have time I'll see what I can do with refactoring etc.
