### ISSUE TITLE
Suggestion: more sophisticated RCS1207 "use method group instead of anonymous function"

### ISSUE THREAD

**Issue by mikernet** [JosefPihrt/Roslynator#644]
RCS1207 detects code like this:

```c#
public static bool TestString(string x) => true;

public string M(IEnumerable<string> x)
{
    return x.FirstOrDefault(x => TestString(x)); // RCS1207
}

// Suggested fix:

public string M(IEnumerable<string> x)
{
    return x.FirstOrDefault(TestString);
}
       
```

But it fails to catch code like the following (credit: @canton7):

```c#
private string originalTarget;

public string M(IEnumerable<string> x)
{
    return x.FirstOrDefault(x => originalTarget.Contains(x));
}

public string M(string e, IEnumerable<string> x)
{
    return x.FirstOrDefault(x => e.Contains(x));
}

// Could be written as:

public string N(IEnumerable<string> x)
{
    return x.FirstOrDefault(originalTarget.Contains);
}

public string N(string e, IEnumerable<string> x)
{
    return x.FirstOrDefault(e.Contains);
}
```

**Comment by JosefPihrt** [comment]
Proposed behavior was disabled in #257. The reason is that the code before and after the fix are not equivalent. Please see code sample in [SharpLab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQMwAJboGIHtfIDey6pmGUcADOgEICGATgBQCU6AvAHzoBEDjXgG5kJMmkxwAbJgAs6AKoBnAKYAZegFsARsHpsxpYkjKn0ANyboAZvk7oAdioDuOfGxFJDZqAFYAPJRUPNYArg4AxvZsnCH4AHQCHqImZqSUAJzMYZFsrELoAPSFfAK8KWmktrj2DqEANvWe3qaZ2eEReQXF6AByDfUASirWKowqkSoAogAeESoADgAuAJa4Dt4AvhXiFNJyiqoAsipLABa4wADijLihCwapRi1klow2dhyOLm64yV5PHwBIIhDr2aqJJjNQGtOBZHKdVj5IolfhMcoAyofGpfOqNaFYtoIroo0rorbITZAA==).

**Comment by mikernet** [comment]
Ah, right, that definitely makes sense.
