### ISSUE TITLE
Faded out types even with features turned off

### ISSUE THREAD

**Issue by kornelijepetak** [JosefPihrt/Roslynator#68]
I have disabled all refactorings from Roslynator options, but I still have a lightbulb suggesting "use 'var' instead of explicit type'. Also, the type is faded out.

![image](https://cloud.githubusercontent.com/assets/7033216/24144578/159b65f6-0e2e-11e7-8a24-8bf8b5496de2.png)

![image](https://cloud.githubusercontent.com/assets/7033216/24144557/fe3ec862-0e2d-11e7-9263-146c76aaa39b.png)

Shouldn't the type be left as is if that option is disabled?

**Comment by JosefPihrt** [comment]
Hi,

it seems you are referring to analyzer (not refactoring) "Use 'var' instead of explicit type (when the type is obvious)" (RCS1010). Analyzers cannot be disabled from Visual Studio options, you have to use **rule set**. Please see [How to Customize Analyzers](https://github.com/JosefPihrt/Roslynator/blob/master/docs/HowToCustomizeAnalyzers.md).

I understand that there is confusion between analyzers and refactorings. That is why I added identifier 'RR....' to each refactoring to distinguished them from analyzers which have identifier 'RCS....'.

**Comment by kornelijepetak** [comment]
You are right. The code visual style is modified by analyzers, not refactorings. Great plugin, by the way. Well done!

**Comment by JosefPihrt** [comment]
Thanks!
