### ISSUE TITLE
RCS1097 false positive when using pre-processor directives

### ISSUE THREAD

**Issue by elachlan** [JosefPihrt/Roslynator#706]
**Product and Version Used**: 
3.0.0

**Steps to Reproduce**:
It found the ToString() here:
https://github.com/dotnet/msbuild/blob/fd9321acc2cb181118fb73d83bf243fa7d77494a/src/Shared/FileUtilities.cs#L457-L467

**Actual Behavior**:
Replaced.

**Expected Behavior**:
Do not replace/detect.

**Comment by JosefPihrt** [comment]
This behavior is by design.

If you compile the source with "FEATURE_SPAN" defined the diagnostic will not be reported. If you compile the source without "FEATURE_SPAN" defined the diagnostic will be reported.

Suitable solution to this issue is to suppress the diagnostic:
https://github.com/JosefPihrt/Roslynator/blob/master/docs/HowToConfigureAnalyzers.md#suppress-diagnostics
