### ISSUE TITLE
VSCode doesn't show warnings

### ISSUE THREAD

**Issue by imperugo** [JosefPihrt/Roslynator#742]
Hi, 
I've installed the latest version (v3.0.1) of Roslynator for VSCode.
It works pretty well (congrats for the project) with almost all the projects except for a solution that is probably too big (66 projects all built on top of .NET Core 3.1).

I'm pretty sure my code is good, but not enough to be "roslynator free" in fact, if I add the analyser a build time I've several errors. Moreover if I open the solution with Visual Studio instead of VSCode the analyzer works perfectly, I can see the warnings.

Last but not least, the problem with this solution happens both on Windows and Mac.
Any hint?

**Comment by JosefPihrt** [comment]
If the analyzers do not show at all in the big solution and it does show up in other smaller solutions I would guess that the problem is not related to Roslynator but rather to the engine that executes Roslyn analyzers (which is OmniSharp).

Could you try to use some other set of analyzers in big solution to see if they show up or not?

**Comment by imperugo** [comment]
Hi @JosefPihrt 
thanks for the quick answer.
I've used for months `StyleCop.Analyzers` before to find `Roslynator` and it works fine. Do you have any other to test?

**Comment by JosefPihrt** [comment]
https://github.com/u2uconsult/codeanalyzers
https://github.com/code-cracker/code-cracker
https://github.com/icsharpcode/RefactoringEssentials

**Comment by JosefPihrt** [comment]
@imperugo any update?
