### ISSUE TITLE
Roslynator.DotNet.Cli wants to return a non-zero code if one or more diagnostics are found.

### ISSUE THREAD

**Issue by ikuosaito1989** [JosefPihrt/Roslynator#759]
**Product and Version Used**: 
Roslynator.DotNet.Cli 0.1.1

**Steps to Reproduce**:
```bash
dotnet roslynator analyze
```

**Actual Behavior**:
Even if a diagnostic is found, the exit code returns 0, so it cannot be detected by CI, etc.
```bash
---------------------------------------------
Roslynator Command Line Tool version 0.1.1.0
Copyright (c) Josef Pihrt. All rights reserved.

...

5 diagnostics found
---------------------------------------------

↓

exit 0
```

**Expected Behavior**:
As with [dotnet format](https://github.com/dotnet/format), the -check option returns a non-zero code.
```bash
---------------------------------------------
Roslynator Command Line Tool version 0.1.1.0
Copyright (c) Josef Pihrt. All rights reserved.

...

5 diagnostics found
---------------------------------------------

↓

exit 1
```

**Comment by ikuosaito1989** [comment]
@JosefPihrt 

Thanks for the fix.

**Comment by JosefPihrt** [comment]
@ikuosaito1989 You are welcome.

FYI: There is common convention that the app returns 0 when it finishes successfully. Because of that if the Roslynator CLI finds any diagnostic it returns 0 if it finds no diagnostic it returns 1. It will return 2 when an error occurs or if the execution is canceled.
