### ISSUE TITLE
Dependency on Microsoft.CodeAnalysis v3.7.0.0 in project

### ISSUE THREAD

**Issue by asears** [JosefPihrt/Roslynator#763]
**Product and Version Used**: 
Build in Visual Studio 2019 latest works.
Build in Visual Studio 2019 Enterprise 16.4.0.9 doesn't work.

**Steps to Reproduce**:
Add Rosylnator, CodeAnalysis, Formatters to project
Build in earlier version of Visual Studio.

**Actual Behavior**:
```shell
InitializerAnalyzer cannot be created from C:\users\(myname)\.nuget\packages...
Could not load file or assembly Microsoft.CodeAnalysis, Version=3.7.0.0.
```

**Expected Behavior**:
Solution builds after adding Roslynator dependency.

Is there another package or binding redirect which needs to be added to fix earlier versions builds?

Also, is repo generated documentation for this dependency up-to-date?

**Comment by JosefPihrt** [comment]
The solution to this issue is to install latest VS version. I have installed VS Community 16.8.3 on my machine.

The rule is that the minor version of VS maps to minor version of Roslyn libraries. So when the Roslynator uses Roslyn 3.7.0 you have to use at least VS 16.7.0. Roslyn 3.8.0 is part of VS 16.8.x and so on.

https://docs.microsoft.com/en-us/visualstudio/extensibility/roslyn-version-support?view=vs-2019
