### ISSUE TITLE
Support editorconfig or globalconfig for setting analyzer options

### ISSUE THREAD

**Issue by webczat** [JosefPihrt/Roslynator#804]
I have tried roslynator 3.1.0 and 3.2.0-rc and (the analyzers nuget) and this seems to be still present.
The only way to switch options like RCS1096i, for example, is by using a ruleset file. My intention is to enable this option project/solution wide, but it seems to be the only thing in whole project that does require the ruleset file.
Could that also be supported when using the new .globalconfig, or even .editorconfig? Both seem not to work.

**Comment by JosefPihrt** [comment]
Ruleset options are workaround and it came from a frustration that there was no way how to add options to roslyn analyzers.

From Roslynator 3.2.0 there is built-in support for editorconfig options which is much better because it allows to change options for a given folder (and subfolders).

My recommendation is to migrate to editorconfig options.

To invert RCS1096 on a solution-wide basis please add .editorconfig file to the root folder of your solution and add following lines to that file:
```editorconfig
[*.{cs,csx}]
roslynator.RCS1096.invert = true
```

**Comment by webczat** [comment]
ooooh okay. is that documented already?

**Comment by JosefPihrt** [comment]
https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1096.md#options
