### ISSUE TITLE
Roslynator.CodeAnalysis.Analyzers and Roslynator.Formatting.Analyzers throw System.IO.FileLoadException

### ISSUE THREAD

**Issue by edumserrano** [JosefPihrt/Roslynator#833]
**Product and Version Used**: 

`Roslynator.Analyzers` **3.2.0**
`Roslynator.CodeAnalysis.Analyzers` **1.1.0**
`Roslynator.Formatting.Analyzers` **1.2.1**

`.NET SDK` **5.0.302**

**Steps to Reproduce**:

1) Create a console application targetting net5.0.
2) Add the following Nugets:
    - `Roslynator.Analyzers` **3.2.0**
    - `Roslynator.CodeAnalysis.Analyzers` **1.1.0**
    - `Roslynator.Formatting.Analyzers`  **1.2.1**
3) Build the application: `dotnet build --no-incremental`
4) The output from the build command shows lots of `System.IO.FileLoadException`. Examples: 
    - > CSC : warning AD0001: Analyzer 'Roslynator.CodeAnalysis.CSharp.ElementAccessExpressionAnalyzer' threw an exception of type 'System.IO.FileLoadException' with message 'Could not load file or assembly 'Roslynator.Core, Version=2.1.0.3, Culture=neutral, PublicKeyToken=926ea54d246a765e'. Could not find or load a specific file. (0x80131621)'. [/home/runner/work/dot-net-sdk-extensions/dot-net-sdk-extensions/src/DotNet.Sdk.Extensions.Testing/DotNet.Sdk.Extensions.Testing.csproj]
    - > CSC : warning AD0001: Analyzer 'Roslynator.Formatting.CSharp.AddEmptyLineAfterEmbeddedStatementAnalyzer' threw an exception of type 'System.IO.FileLoadException' with message 'Could not load file or assembly 'Roslynator.Core, Version=2.1.0.3, Culture=neutral, PublicKeyToken=926ea54d246a765e'. Could not find or load a specific file. (0x80131621)'. [/home/runner/work/dot-net-sdk-extensions/dot-net-sdk-extensions/src/DotNet.Sdk.Extensions.Testing/DotNet.Sdk.Extensions.Testing.csproj]

**Actual Behavior**:

There are lots of `System.IO.FileLoadException` warnings produced in the output when using the 3 Nuget packages together. I noticed that if I do **NOT** install the `Roslynator.Analyzers` but install the other 2 then no `System.IO.FileLoadException` warnings are produced. 

I could **NOT** find any version of `Roslynator.Analyzers` that could be used in conjunction with the other two nugets that did not cause this issue.

**Expected Behavior**:

I can use the 3 Nuget packages and **NOT** have the `System.IO.FileLoadException` warnings.

**More info**:

You can see this [GitHub action build log](https://github.com/edumserrano/dot-net-sdk-extensions/runs/3204881307?check_suite_focus=true#step:7:14) for an example of this issue.

**Comment by p-bojkowski** [comment]
The same with 6.0.100-preview.6.21355.2

**Comment by p-bojkowski** [comment]
Maybe related: https://github.com/GuOrg/Gu.Analyzers/issues/315

**Comment by tuananh-le** [comment]
I got the same issue in my .NET 5 project as well. I remember it used to work fine before. Any workarounds for now?

**Comment by JosefPihrt** [comment]
I'm working on a solution to this issue.

It is caused by the way how .NET Core load assemblies.

I relied on the fact that if there are strongly named assemblies with same name but different versions the runtime will load the assembly with the exact version. This behavior works on .NET Framework but not on .NET Core.

I found issue that describes very similar problem: https://github.com/dotnet/roslyn/issues/41421

One possible solution suggested there is to use `ILMerge` or similar tool to embed shared dlls.

Another solution which I will probably choose is to rename shared assemblies to enforce that it will be correctly loaded. The shared assembly `Roslynator.Core.dll` would be renamed as follows:
* `Roslynator_Analyzers_Roslynator.Core.dll` in package `Roslynator.Analyzers`
* `Roslynator_Formatting_Analyzers_Roslynator.Core.dll` in package `Roslynator.Formatting.Analyzers`
* `Roslynator_CodeAnalysis_Analyzers_Roslynator.Core.dll` in package `Roslynator.CodeAnalysis.Analyzers`

The same pattern would be applied on other shared assemblies.

**Comment by fgimian** [comment]
Thank you so much @JosefPihrt! 😄

**Comment by fgimian** [comment]
Thanks so much for sorting this one out @JosefPihrt!!! 🥳

**Comment by sid-6581** [comment]
Has this been fixed, or is a fix still coming? I'm having this problem as well, even on 3.3.0-rc. I just use `Roslynator.Analyzers` and `Roslynator.Formatting.Analyzers`.

**Comment by JosefPihrt** [comment]
@sid-6581 Please file new issue and describe the problem there, Thanks.
