### ISSUE TITLE
RCS0020 vs RCS0043

### ISSUE THREAD

**Issue by sungam3r** [JosefPihrt/Roslynator#857]
**Product and Version Used**: 

Roslynator.Analyzers 3.2.2
Roslynator.Formatting.Analyzers 1.2.2

**Steps to Reproduce**:
```csharp

public class StreamWriterAdapter : StreamWriter
{
 public override bool AutoFlush
 {
         get => true;
         set { }
  }
}
```
yields `RCS0020	Add newline after opening brace of accessor.`

After applying fix:
```csharp
public override bool AutoFlush
{
        get => true;
        set
        {
        }
}
```
`RCS0043	Remove newlines from accessor with single-line expression.` 😞 

I expect that the rules will not contradict each other. I would prefer RCS0043 over RCS0020.

**Comment by JosefPihrt** [comment]
I think that these two analyzers are mutually exclusive so you can enable one or the other not both.

**Comment by sungam3r** [comment]
OK, thanks.

**Comment by JosefPihrt** [comment]
I thought about it one more time and it turned out that you actually made right point. So I decided to implement your request in a following way:

RCS0043 will be deprecated in favor of new config option `roslynator_accessor_braces_style`

So if you would like to format accessor's braces to multiple lines except those that are empty or contains single-line statement you would add following lines to your editor config file:

```editorconfig
dotnet_diagnostic.RCS0020.severity = info
roslynator_accessor_braces_style = single_line_when_statement_is_on_single_line
```

**Comment by sungam3r** [comment]
Thanks.
