### ISSUE TITLE
Extract type to new file includes unneeded attributes and using directives

### ISSUE THREAD

**Issue by xt0rted** [JosefPihrt/Roslynator#96]
**Version Used:** 1.3.11

The extract type to new file refactoring duplicates assembly level attributes that are in the source file, along with copying all using directives not just the ones that are required by the destination type.

The built-in move type to file refactoring only copies the using directives that are needed by the destination type. There's a bug in this refactoring that dupes the assembly level attributes that's been reported at https://github.com/dotnet/roslyn/issues/19707.

Since a refactoring already exists for this functionality would it be better to piggy back on that instead of trying to recreate it? By the looks of it the built-in one is more advanced as well https://github.com/dotnet/roslyn/pull/12624.

**Comment by JosefPihrt** [comment]
This is common case where existing refactoring had been later implemented by Microsoft and now there are two refactorings with same (or similar) functionality. You can disable Roslynator refactoring in Visual Studio options.

Preservation of all directives is intentional. It depends on personal preferences. I like to keep all directives so I don't have to add it into new file (it is common case that code in the new file use similar namespaces).

I agree that assembly attributes should be removed, I'll fix it.
